//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnoBIT_Wallet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SpecialFolder.ApplicationData")]
        public string RootPath {
            get {
                return ((string)(this["RootPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AnoBIT")]
        public string RootPathFolder {
            get {
                return ((string)(this["RootPathFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("abandon,ability,able,about,above,absent,absorb,abstract,absurd,abuse,access,accid" +
            "ent,account,accuse,achieve,acid,acoustic,acquire,across,act,action,actor,actress" +
            ",actual,adapt,add,addict,address,adjust,admit,adult,advance,advice,aerobic,affai" +
            "r,afford,afraid,again,age,agent,agree,ahead,aim,air,airport,aisle,alarm,album,al" +
            "cohol,alert,alien,all,alley,allow,almost,alone,alpha,already,also,alter,always,a" +
            "mateur,amazing,among,amount,amused,analyst,anchor,ancient,anger,angle,angry,anim" +
            "al,ankle,announce,annual,another,answer,antenna,antique,anxiety,any,apart,apolog" +
            "y,appear,apple,approve,april,arch,arctic,area,arena,argue,arm,armed,armor,army,a" +
            "round,arrange,arrest,arrive,arrow,art,artefact,artist,artwork,ask,aspect,assault" +
            ",asset,assist,assume,asthma,athlete,atom,attack,attend,attitude,attract,auction," +
            "audit,august,aunt,author,auto,autumn,average,avocado,avoid,awake,aware,away,awes" +
            "ome,awful,awkward,axis,baby,bachelor,bacon,badge,bag,balance,balcony,ball,bamboo" +
            ",banana,banner,bar,barely,bargain,barrel,base,basic,basket,battle,beach,bean,bea" +
            "uty,because,become,beef,before,begin,behave,behind,believe,below,belt,bench,bene" +
            "fit,best,betray,better,between,beyond,bicycle,bid,bike,bind,biology,bird,birth,b" +
            "itter,black,blade,blame,blanket,blast,bleak,bless,blind,blood,blossom,blouse,blu" +
            "e,blur,blush,board,boat,body,boil,bomb,bone,bonus,book,boost,border,boring,borro" +
            "w,boss,bottom,bounce,box,boy,bracket,brain,brand,brass,brave,bread,breeze,brick," +
            "bridge,brief,bright,bring,brisk,broccoli,broken,bronze,broom,brother,brown,brush" +
            ",bubble,buddy,budget,buffalo,build,bulb,bulk,bullet,bundle,bunker,burden,burger," +
            "burst,bus,business,busy,butter,buyer,buzz,cabbage,cabin,cable,cactus,cage,cake,c" +
            "all,calm,camera,camp,can,canal,cancel,candy,cannon,canoe,canvas,canyon,capable,c" +
            "apital,captain,car,carbon,card,cargo,carpet,carry,cart,case,cash,casino,castle,c" +
            "asual,cat,catalog,catch,category,cattle,caught,cause,caution,cave,ceiling,celery" +
            ",cement,census,century,cereal,certain,chair,chalk,champion,change,chaos,chapter," +
            "charge,chase,chat,cheap,check,cheese,chef,cherry,chest,chicken,chief,child,chimn" +
            "ey,choice,choose,chronic,chuckle,chunk,churn,cigar,cinnamon,circle,citizen,city," +
            "civil,claim,clap,clarify,claw,clay,clean,clerk,clever,click,client,cliff,climb,c" +
            "linic,clip,clock,clog,close,cloth,cloud,clown,club,clump,cluster,clutch,coach,co" +
            "ast,coconut,code,coffee,coil,coin,collect,color,column,combine,come,comfort,comi" +
            "c,common,company,concert,conduct,confirm,congress,connect,consider,control,convi" +
            "nce,cook,cool,copper,copy,coral,core,corn,correct,cost,cotton,couch,country,coup" +
            "le,course,cousin,cover,coyote,crack,cradle,craft,cram,crane,crash,crater,crawl,c" +
            "razy,cream,credit,creek,crew,cricket,crime,crisp,critic,crop,cross,crouch,crowd," +
            "crucial,cruel,cruise,crumble,crunch,crush,cry,crystal,cube,culture,cup,cupboard," +
            "curious,current,curtain,curve,cushion,custom,cute,cycle,dad,damage,damp,dance,da" +
            "nger,daring,dash,daughter,dawn,day,deal,debate,debris,decade,december,decide,dec" +
            "line,decorate,decrease,deer,defense,define,defy,degree,delay,deliver,demand,demi" +
            "se,denial,dentist,deny,depart,depend,deposit,depth,deputy,derive,describe,desert" +
            ",design,desk,despair,destroy,detail,detect,develop,device,devote,diagram,dial,di" +
            "amond,diary,dice,diesel,diet,differ,digital,dignity,dilemma,dinner,dinosaur,dire" +
            "ct,dirt,disagree,discover,disease,dish,dismiss,disorder,display,distance,divert," +
            "divide,divorce,dizzy,doctor,document,dog,doll,dolphin,domain,donate,donkey,donor" +
            ",door,dose,double,dove,draft,dragon,drama,drastic,draw,dream,dress,drift,drill,d" +
            "rink,drip,drive,drop,drum,dry,duck,dumb,dune,during,dust,dutch,duty,dwarf,dynami" +
            "c,eager,eagle,early,earn,earth,easily,east,easy,echo,ecology,economy,edge,edit,e" +
            "ducate,effort,egg,eight,either,elbow,elder,electric,elegant,element,elephant,ele" +
            "vator,elite,else,embark,embody,embrace,emerge,emotion,employ,empower,empty,enabl" +
            "e,enact,end,endless,endorse,enemy,energy,enforce,engage,engine,enhance,enjoy,enl" +
            "ist,enough,enrich,enroll,ensure,enter,entire,entry,envelope,episode,equal,equip," +
            "era,erase,erode,erosion,error,erupt,escape,essay,essence,estate,eternal,ethics,e" +
            "vidence,evil,evoke,evolve,exact,example,excess,exchange,excite,exclude,excuse,ex" +
            "ecute,exercise,exhaust,exhibit,exile,exist,exit,exotic,expand,expect,expire,expl" +
            "ain,expose,express,extend,extra,eye,eyebrow,fabric,face,faculty,fade,faint,faith" +
            ",fall,false,fame,family,famous,fan,fancy,fantasy,farm,fashion,fat,fatal,father,f" +
            "atigue,fault,favorite,feature,february,federal,fee,feed,feel,female,fence,festiv" +
            "al,fetch,fever,few,fiber,fiction,field,figure,file,film,filter,final,find,fine,f" +
            "inger,finish,fire,firm,first,fiscal,fish,fit,fitness,fix,flag,flame,flash,flat,f" +
            "lavor,flee,flight,flip,float,flock,floor,flower,fluid,flush,fly,foam,focus,fog,f" +
            "oil,fold,follow,food,foot,force,forest,forget,fork,fortune,forum,forward,fossil," +
            "foster,found,fox,fragile,frame,frequent,fresh,friend,fringe,frog,front,frost,fro" +
            "wn,frozen,fruit,fuel,fun,funny,furnace,fury,future,gadget,gain,galaxy,gallery,ga" +
            "me,gap,garage,garbage,garden,garlic,garment,gas,gasp,gate,gather,gauge,gaze,gene" +
            "ral,genius,genre,gentle,genuine,gesture,ghost,giant,gift,giggle,ginger,giraffe,g" +
            "irl,give,glad,glance,glare,glass,glide,glimpse,globe,gloom,glory,glove,glow,glue" +
            ",goat,goddess,gold,good,goose,gorilla,gospel,gossip,govern,gown,grab,grace,grain" +
            ",grant,grape,grass,gravity,great,green,grid,grief,grit,grocery,group,grow,grunt," +
            "guard,guess,guide,guilt,guitar,gun,gym,habit,hair,half,hammer,hamster,hand,happy" +
            ",harbor,hard,harsh,harvest,hat,have,hawk,hazard,head,health,heart,heavy,hedgehog" +
            ",height,hello,helmet,help,hen,hero,hidden,high,hill,hint,hip,hire,history,hobby," +
            "hockey,hold,hole,holiday,hollow,home,honey,hood,hope,horn,horror,horse,hospital," +
            "host,hotel,hour,hover,hub,huge,human,humble,humor,hundred,hungry,hunt,hurdle,hur" +
            "ry,hurt,husband,hybrid,ice,icon,idea,identify,idle,ignore,ill,illegal,illness,im" +
            "age,imitate,immense,immune,impact,impose,improve,impulse,inch,include,income,inc" +
            "rease,index,indicate,indoor,industry,infant,inflict,inform,inhale,inherit,initia" +
            "l,inject,injury,inmate,inner,innocent,input,inquiry,insane,insect,inside,inspire" +
            ",install,intact,interest,into,invest,invite,involve,iron,island,isolate,issue,it" +
            "em,ivory,jacket,jaguar,jar,jazz,jealous,jeans,jelly,jewel,job,join,joke,journey," +
            "joy,judge,juice,jump,jungle,junior,junk,just,kangaroo,keen,keep,ketchup,key,kick" +
            ",kid,kidney,kind,kingdom,kiss,kit,kitchen,kite,kitten,kiwi,knee,knife,knock,know" +
            ",lab,label,labor,ladder,lady,lake,lamp,language,laptop,large,later,latin,laugh,l" +
            "aundry,lava,law,lawn,lawsuit,layer,lazy,leader,leaf,learn,leave,lecture,left,leg" +
            ",legal,legend,leisure,lemon,lend,length,lens,leopard,lesson,letter,level,liar,li" +
            "berty,library,license,life,lift,light,like,limb,limit,link,lion,liquid,list,litt" +
            "le,live,lizard,load,loan,lobster,local,lock,logic,lonely,long,loop,lottery,loud," +
            "lounge,love,loyal,lucky,luggage,lumber,lunar,lunch,luxury,lyrics,machine,mad,mag" +
            "ic,magnet,maid,mail,main,major,make,mammal,man,manage,mandate,mango,mansion,manu" +
            "al,maple,marble,march,margin,marine,market,marriage,mask,mass,master,match,mater" +
            "ial,math,matrix,matter,maximum,maze,meadow,mean,measure,meat,mechanic,medal,medi" +
            "a,melody,melt,member,memory,mention,menu,mercy,merge,merit,merry,mesh,message,me" +
            "tal,method,middle,midnight,milk,million,mimic,mind,minimum,minor,minute,miracle," +
            "mirror,misery,miss,mistake,mix,mixed,mixture,mobile,model,modify,mom,moment,moni" +
            "tor,monkey,monster,month,moon,moral,more,morning,mosquito,mother,motion,motor,mo" +
            "untain,mouse,move,movie,much,muffin,mule,multiply,muscle,museum,mushroom,music,m" +
            "ust,mutual,myself,mystery,myth,naive,name,napkin,narrow,nasty,nation,nature,near" +
            ",neck,need,negative,neglect,neither,nephew,nerve,nest,net,network,neutral,never," +
            "news,next,nice,night,noble,noise,nominee,noodle,normal,north,nose,notable,note,n" +
            "othing,notice,novel,now,nuclear,number,nurse,nut,oak,obey,object,oblige,obscure," +
            "observe,obtain,obvious,occur,ocean,october,odor,off,offer,office,often,oil,okay," +
            "old,olive,olympic,omit,once,one,onion,online,only,open,opera,opinion,oppose,opti" +
            "on,orange,orbit,orchard,order,ordinary,organ,orient,original,orphan,ostrich,othe" +
            "r,outdoor,outer,output,outside,oval,oven,over,own,owner,oxygen,oyster,ozone,pact" +
            ",paddle,page,pair,palace,palm,panda,panel,panic,panther,paper,parade,parent,park" +
            ",parrot,party,pass,patch,path,patient,patrol,pattern,pause,pave,payment,peace,pe" +
            "anut,pear,peasant,pelican,pen,penalty,pencil,people,pepper,perfect,permit,person" +
            ",pet,phone,photo,phrase,physical,piano,picnic,picture,piece,pig,pigeon,pill,pilo" +
            "t,pink,pioneer,pipe,pistol,pitch,pizza,place,planet,plastic,plate,play,please,pl" +
            "edge,pluck,plug,plunge,poem,poet,point,polar,pole,police,pond,pony,pool,popular," +
            "portion,position,possible,post,potato,pottery,poverty,powder,power,practice,prai" +
            "se,predict,prefer,prepare,present,pretty,prevent,price,pride,primary,print,prior" +
            "ity,prison,private,prize,problem,process,produce,profit,program,project,promote," +
            "proof,property,prosper,protect,proud,provide,public,pudding,pull,pulp,pulse,pump" +
            "kin,punch,pupil,puppy,purchase,purity,purpose,purse,push,put,puzzle,pyramid,qual" +
            "ity,quantum,quarter,question,quick,quit,quiz,quote,rabbit,raccoon,race,rack,rada" +
            "r,radio,rail,rain,raise,rally,ramp,ranch,random,range,rapid,rare,rate,rather,rav" +
            "en,raw,razor,ready,real,reason,rebel,rebuild,recall,receive,recipe,record,recycl" +
            "e,reduce,reflect,reform,refuse,region,regret,regular,reject,relax,release,relief" +
            ",rely,remain,remember,remind,remove,render,renew,rent,reopen,repair,repeat,repla" +
            "ce,report,require,rescue,resemble,resist,resource,response,result,retire,retreat" +
            ",return,reunion,reveal,review,reward,rhythm,rib,ribbon,rice,rich,ride,ridge,rifl" +
            "e,right,rigid,ring,riot,ripple,risk,ritual,rival,river,road,roast,robot,robust,r" +
            "ocket,romance,roof,rookie,room,rose,rotate,rough,round,route,royal,rubber,rude,r" +
            "ug,rule,run,runway,rural,sad,saddle,sadness,safe,sail,salad,salmon,salon,salt,sa" +
            "lute,same,sample,sand,satisfy,satoshi,sauce,sausage,save,say,scale,scan,scare,sc" +
            "atter,scene,scheme,school,science,scissors,scorpion,scout,scrap,screen,script,sc" +
            "rub,sea,search,season,seat,second,secret,section,security,seed,seek,segment,sele" +
            "ct,sell,seminar,senior,sense,sentence,series,service,session,settle,setup,seven," +
            "shadow,shaft,shallow,share,shed,shell,sheriff,shield,shift,shine,ship,shiver,sho" +
            "ck,shoe,shoot,shop,short,shoulder,shove,shrimp,shrug,shuffle,shy,sibling,sick,si" +
            "de,siege,sight,sign,silent,silk,silly,silver,similar,simple,since,sing,siren,sis" +
            "ter,situate,six,size,skate,sketch,ski,skill,skin,skirt,skull,slab,slam,sleep,sle" +
            "nder,slice,slide,slight,slim,slogan,slot,slow,slush,small,smart,smile,smoke,smoo" +
            "th,snack,snake,snap,sniff,snow,soap,soccer,social,sock,soda,soft,solar,soldier,s" +
            "olid,solution,solve,someone,song,soon,sorry,sort,soul,sound,soup,source,south,sp" +
            "ace,spare,spatial,spawn,speak,special,speed,spell,spend,sphere,spice,spider,spik" +
            "e,spin,spirit,split,spoil,sponsor,spoon,sport,spot,spray,spread,spring,spy,squar" +
            "e,squeeze,squirrel,stable,stadium,staff,stage,stairs,stamp,stand,start,state,sta" +
            "y,steak,steel,stem,step,stereo,stick,still,sting,stock,stomach,stone,stool,story" +
            ",stove,strategy,street,strike,strong,struggle,student,stuff,stumble,style,subjec" +
            "t,submit,subway,success,such,sudden,suffer,sugar,suggest,suit,summer,sun,sunny,s" +
            "unset,super,supply,supreme,sure,surface,surge,surprise,surround,survey,suspect,s" +
            "ustain,swallow,swamp,swap,swarm,swear,sweet,swift,swim,swing,switch,sword,symbol" +
            ",symptom,syrup,system,table,tackle,tag,tail,talent,talk,tank,tape,target,task,ta" +
            "ste,tattoo,taxi,teach,team,tell,ten,tenant,tennis,tent,term,test,text,thank,that" +
            ",theme,then,theory,there,they,thing,this,thought,three,thrive,throw,thumb,thunde" +
            "r,ticket,tide,tiger,tilt,timber,time,tiny,tip,tired,tissue,title,toast,tobacco,t" +
            "oday,toddler,toe,together,toilet,token,tomato,tomorrow,tone,tongue,tonight,tool," +
            "tooth,top,topic,topple,torch,tornado,tortoise,toss,total,tourist,toward,tower,to" +
            "wn,toy,track,trade,traffic,tragic,train,transfer,trap,trash,travel,tray,treat,tr" +
            "ee,trend,trial,tribe,trick,trigger,trim,trip,trophy,trouble,truck,true,truly,tru" +
            "mpet,trust,truth,try,tube,tuition,tumble,tuna,tunnel,turkey,turn,turtle,twelve,t" +
            "wenty,twice,twin,twist,two,type,typical,ugly,umbrella,unable,unaware,uncle,uncov" +
            "er,under,undo,unfair,unfold,unhappy,uniform,unique,unit,universe,unknown,unlock," +
            "until,unusual,unveil,update,upgrade,uphold,upon,upper,upset,urban,urge,usage,use" +
            ",used,useful,useless,usual,utility,vacant,vacuum,vague,valid,valley,valve,van,va" +
            "nish,vapor,various,vast,vault,vehicle,velvet,vendor,venture,venue,verb,verify,ve" +
            "rsion,very,vessel,veteran,viable,vibrant,vicious,victory,video,view,village,vint" +
            "age,violin,virtual,virus,visa,visit,visual,vital,vivid,vocal,voice,void,volcano," +
            "volume,vote,voyage,wage,wagon,wait,walk,wall,walnut,want,warfare,warm,warrior,wa" +
            "sh,wasp,waste,water,wave,way,wealth,weapon,wear,weasel,weather,web,wedding,weeke" +
            "nd,weird,welcome,west,wet,whale,what,wheat,wheel,when,where,whip,whisper,wide,wi" +
            "dth,wife,wild,will,win,window,wine,wing,wink,winner,winter,wire,wisdom,wise,wish" +
            ",witness,wolf,woman,wonder,wood,wool,word,work,world,worry,worth,wrap,wreck,wres" +
            "tle,wrist,write,wrong,yard,year,yellow,you,young,youth,zebra,zero,zone,zoo")]
        public string AlphaWordlist {
            get {
                return ((string)(this["AlphaWordlist"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int AddressCountPregen {
            get {
                return ((int)(this["AddressCountPregen"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string IP {
            get {
                return ((string)(this["IP"]));
            }
            set {
                this["IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6777")]
        public ushort Port {
            get {
                return ((ushort)(this["Port"]));
            }
            set {
                this["Port"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort ReplayProtection {
            get {
                return ((ushort)(this["ReplayProtection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string ServerPublicKey {
            get {
                return ((string)(this["ServerPublicKey"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int UINotifyTimeout {
            get {
                return ((int)(this["UINotifyTimeout"]));
            }
            set {
                this["UINotifyTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public int PocketingThreshold {
            get {
                return ((int)(this["PocketingThreshold"]));
            }
            set {
                this["PocketingThreshold"] = value;
            }
        }
    }
}
